// Completed by Hemza Al Shamari
// 04/30/23
// hemzas@uw.edu

#include "edge.h"

// Default constructor: initializes "from" and "to" vertices to null and weight
// to 0
Edge::Edge() {
  this->from = nullptr;
  this->to = nullptr;
  this->weight = 0;
}

// Constructor that takes two vertices and a weight and sets the member
// variables accordingly
Edge::Edge(Vertex *vFrom, Vertex *vTo, int weight) {
  this->from = vFrom;
  this->to = vTo;
  this->weight = weight;
}

// Destructor: automatically generated by the compiler and frees memory used by
// the Edge object when it is destroyed
Edge::~Edge() = default;